name: ClearReleasesAndTags

on:
  schedule:
    - cron: '50 22 * * 0'
  workflow_dispatch:

jobs:
  clearReleasesAndTags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete Releases and Tags
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          
          releases=$(curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/1ookilo/HMS-TH/releases")
          for release in $(echo "$releases" | jq -r '.[] | .id'); do
            echo "Deleting release $release..."
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/1ookilo/HMS-TH/releases/$release"
          done

      - name: Delete Tags
        run: |
          git fetch --prune --tags
          tags=$(git tag -l)
          for tag in $tags; do
            git push origin --delete $tag
          done
